import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { ReconciliationEngine } from "../src/web/core/reconciliation";
import { generateReconciliationJson } from "../src/web/core/export";
import { ReconciliationContract } from "../src/web/core/types";
import { parseCsvContent } from "../src/web/analysis/csv";

describe("Python JSON schema parity", () => {
  it("validates a report generated by the browser exporter", () => {
    const fixture = resolve(__dirname, "fixtures/python_reference/core_hr_vs_payroll");
    const source = JSON.parse(readFileSync(join(fixture, "contract.json"), "utf8"));
    const contract: ReconciliationContract = {
      name: source.name, left: { name: source.left.name }, right: { name: source.right.name },
      identity: source.identity,
      fields: source.fields.map((f: Record<string, any>) => ({ name: f.name, left: f.left, right: f.right, normalize: f.normalize ?? [], valueMapping: f.value_mapping ?? null })),
      valueMappings: Object.fromEntries(Object.entries(source.value_mappings).map(([name, values]) => [name, Object.fromEntries(Object.entries(values as Record<string, any>).map(([canonical, v]) => [canonical, v]))])),
    };
    const left = parseCsvContent(readFileSync(join(fixture, "core_hr.csv"), "utf8"), "core_hr");
    const right = parseCsvContent(readFileSync(join(fixture, "payroll.csv"), "utf8"), "payroll");
    const result = new ReconciliationEngine().reconcile({ contract, leftDataset: left, rightDataset: right });
    const directory = mkdtempSync(join(tmpdir(), "hris-web-parity-"));
    const report = join(directory, "report.json");
    try {
      writeFileSync(report, generateReconciliationJson(contract, result));
      const root = resolve(__dirname, "..");
      const python = resolve(root, ".venv/bin/python");
      const output = execFileSync(python, ["scripts/validate_web_report.py", report], { cwd: root, encoding: "utf8" });
      expect(output).toMatch(/valid Python ReconciliationReport v1\.0/);
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  });
});
