#!/usr/bin/env python3
"""Generate the browser's pinned Python-compatible Unicode tables."""

from __future__ import annotations

import argparse
import json
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/web/core/unicode_casefold.ts"


def generated() -> str:
    folds = {
        chr(codepoint): chr(codepoint).casefold()
        for codepoint in range(sys.maxunicode + 1)
        if chr(codepoint).casefold() != chr(codepoint)
    }
    whitespace = [chr(codepoint) for codepoint in range(sys.maxunicode + 1) if chr(codepoint).isspace()]
    header = (
        "// Generated by scripts/generate_web_unicode_data.py; do not edit.\n"
        f"// Python {sys.version_info.major}.{sys.version_info.minor}; Unicode {unicodedata.unidata_version}.\n"
    )
    return header + "export const CASEFOLD_TABLE: Record<string, string> = " + json.dumps(folds, ensure_ascii=True, separators=(",", ":")) + ";\n" + "export const PYTHON_WHITESPACE_CODEPOINTS = " + json.dumps([ord(char) for char in whitespace]) + " as const;\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generated()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"generated Unicode data differs: {OUTPUT}", file=sys.stderr)
            return 1
        print(f"Unicode data matches Python {sys.version_info.major}.{sys.version_info.minor} / {unicodedata.unidata_version}")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT} using Python {sys.version_info.major}.{sys.version_info.minor} / Unicode {unicodedata.unidata_version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
